[package]
name = "iqs231"
version = "0.3.0"
edition = "2021"

[dependencies]
defmt = { version = "0.3.8", optional = true }
embedded-hal = "0.2" # We support eh v0.2.x now

bitflags = "2.9" # bitflags is used for simple flag definitions, where each bit represents a boolean flag.
modular-bitfield = "0.12" # modular-bitfield is used for more complex structures where fields can have different bit widths.
num_enum = { version = "0.7", default-features = false }

[features]
defmt = ["dep:defmt"]
